### ISSUE TITLE
load model issue

### ISSUE THREAD

**Issue by Vincent6896** [facebookresearch/mae_st#13]
Thank you for your amazing work. 
I encounter some issues when running the run_test.py. It shows the following error message when loading the checkpoint of the model. I download the weight and does not make any modification. Could you please help me solve this problem? Thank you very much. 

RuntimeError: Error(s) in loading state_dict for VisionTransformer:
size mismatch for patch_embed.proj.weight: copying a param with shape torch.Size([1024, 3, 2, 16, 16]) from checkpoint, the shape in current model is torch.Size([1024, 3, 4, 16, 16]).

Also for the huge one.
And for the pos_embed.py, the "pos_embed" does not in checkpoint_model, so it will never enter the interpolate_pos_embed function. May I ask how to solve this size mismatch error？

**Comment by xyr99sn** [comment]
Hi, we also have this problem when loading the model. Could you have a solution here?

**Comment by Abhinandan707** [comment]
Hey @Vincent6896 , @shownxiao ,

Did you guys find any solution to this problem?

**Comment by shownxiao** [comment]
Not yet, @Abhinandan707, this problem still exists.
