### ISSUE TITLE
what is path_to_video_1 represents for? Does it mean the path to find the video in the folder? Eg. /dataset/video/video1.mp4

### ISSUE THREAD

**Issue by XinyangHan** [facebookresearch/mae_st#18]
Hi, may I ask what is path_to_video_1 represents for? Does it mean the path to find the video in the folder? Eg. /dataset/video/video1.mp4

**Comment by Liu-arch** [comment]
Have you completed the construction of the xxx.csv file? Can you share it with me? Thank you!
