### ISSUE TITLE
How to start multi-gpu training?

### ISSUE THREAD

**Issue by jinga-lala** [facebookresearch/mae_st#4]
Hi, Thank you authors for releasing the code.
 
I have been trying to run `run_pretrain.py` which calls  `main()` function in `main_pretrain.py`. However, it spawns a single GPU run. The function `launch_one_thread()` is not called anywhere. 
Is there any flag that needs to be passed for starting multi-gpu training or there needs to be some changes in the code?
Any help would be highly appreciated.

Thanks

**Comment by haooooooqi** [comment]
Hi @jinga-lala,
The only thing you need to do is to spawn the function of launch_one_thread() on multiple GPUs.
One example you may find helpful is [here](https://github.com/facebookresearch/mae/blob/main/submitit_pretrain.py)
