### ISSUE TITLE
Why repeated sampling does not affect the actual learning rate?

### ISSUE THREAD

**Issue by youcaiSUN** [facebookresearch/mae_st#5]
Hi! Thanks for your great work!

The repeat sampling trick increases the actual batch size (although they come from the same video), however, the actual learning rate is not scaled by the number of repeated samples.

https://github.com/facebookresearch/mae_st/blob/d752324a4a59aab6454236f33b0cd5849f1e600a/main_pretrain.py#L280-L283

I wonder why?

**Comment by haooooooqi** [comment]
Hi, @youcaiSUN,
Thanks for the question. The linear scaling by batch size has already absorbed into the current learning rate. We intentionally kept the repeat sampling out of the lr scaling logic, so the effective epochs would not affect the learning rate.
