### ISSUE TITLE
Dataset and actually running issues

### ISSUE THREAD

**Issue by Vincent6896** [facebookresearch/mae_st#6]
Hi. I encounter some errors when running run_finetune.py, run_pretrain.py, run_test.py.
May I ask how I could find the proper training, testing and val.csv? Should we use the one downloaded from kinetics400 directly? If so, may I ask how to do some modification on the data? It seems that the train/test.csv should have only two columns, path and label. But i did not find path column in the downloaded files. 

In addition, may I ask could you share the download links for the dataset? Thank you very much.

Lastly, may I ask what is the slowfast installation used for in this project?

**Comment by haooooooqi** [comment]
Hi @Vincent6896,

Thanks so much for sharing your questions.
Regarding to the dataset preparation, you can feel free to follow the instruction from [here](https://github.com/facebookresearch/mae_st/blob/main/DATASET.md). For specific details about Kinetics, feel free to check [dataset provider](https://deepmind.com/research/open-source/kinetics).

**Comment by Vincent6896** [comment]
Hi, may I ask what is path_to_video_1 represents for? Does it mean the path to find the video in the folder? Eg. /dataset/video/video1.mp4

**Comment by XinyangHan** [comment]
Hi, may I ask what is path_to_video_1 represents for? Does it mean the path to find the video in the folder? Eg. /dataset/video/video1.mp4
