### ISSUE TITLE
Finetune

### ISSUE THREAD

**Issue by Huiimin5** [facebookresearch/mae_st#7]
Hi,

Thank you so much for sharing the code of this amazing work! Is it possible to also share finetuning for image classification? Current main_finetune.py seems to support Kinetics finetuning only. The parameter "data_path" directs to imagenet directory but is not actually used. Thank you in advance!

Best

**Comment by haooooooqi** [comment]
Hi @Huiimin5,

Could you please kindly remind how would you plan to finetune the pretrain model with 3D(THW) input on a 2D (HW) dataset as imagenet?

**Comment by haooooooqi** [comment]
Hi @Huiimin5,
Thanks for sharing the interesting idea. We currently don't show any experiment for video to image, and imagenet loading might be irrelevant to mae_st repo. 
If you interested in video to image as a new research work, maybe you could the reference impl from the [MAE](https://github.com/facebookresearch/mae) repo.

Thanks
