### ISSUE TITLE
Encoder

### ISSUE THREAD

**Issue by Vincent6896** [facebookresearch/mae_st#8]
Hi.
Thank you for providing amazing work. May I ask could you please share some ideas to extract the feature of the input video? The feature is the one that the encoder extracted from the visiable patches but has not include any mask token. In addition, may I ask whether the run_test is for conducting the mae reconstruction by using the pretrained weight? How the run_test be used to the datasets besides kinetics-400 eg.live_vqc. Thank you very much.

**Comment by Vincent6896** [comment]
Hi. May I ask what is the label in kinetics.py means in line 175?   It seems to be a int value.  (path, label = path_label.split())

**Comment by haooooooqi** [comment]
Hi, 
The label is the corresponding Kinetics label as we following the standard protocal of dataset preparation. You can reference more into details to the [Kinetics](https://www.deepmind.com/open-source/kinetics). The data loader is adapted from (PySlowFast)[https://github.com/facebookresearch/SlowFast].

**Comment by Vincent6896** [comment]
Hi. When I load the pretrained weight of the model it always shows the RuntimeError: Error(s) in loading state_dict for VisionTransformer:
	size mismatch for patch_embed.proj.weight: copying a param with shape torch.Size([1024, 3, 2, 16, 16]) from checkpoint, the shape in current model is torch.Size([1024, 3, 4, 16, 16]).
Also for the huge one. 
And for the pos_embed.py, the "pos_embed" does not in checkpoint_model, so it will never enter the interpolate_pos_embed function. May I ask how to solve this size mismatch error？ Thank you very much.
